In [1]:
%pip install pandas numpy matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print("hello world")
data = pd.read_csv('data/movies.csv')
data

hello world


Unnamed: 0        id original_language               original_title  \
0              0  580489.0                en  Venom: Let There Be Carnage   
1              1  524434.0                en                     Eternals   
2              2  438631.0                en                         Dune   
3              3  796499.0                en              Army of Thieves   
4              4  550988.0                en                     Free Guy   
...          ...       ...               ...                          ...   
10009       9995     530.0                en              A Grand Day Out   
10010       9996   15934.0                en                  El cantante   
10011       9997  162215.0                en               How I Live Now   
10012       9998    5723.0                en                         Once   
10013       9999  311667.0                en              Manhattan Night   

       popularity release_date  vote_average  vote_count  \
0        5401.308   2021-09-30           6.8      1736.0   
1        3365.535   2021-11-03           7.1       622.0   
2        2911.423   2021-09-15           8.0      3632.0   
3        2552.437   2021-10-27           6.9       555.0   
4        1850.470   2021-08-11           7.8      3493.0   
...           ...          ...           ...         ...   
10009       9.266   1990-05-18           7.5       594.0   
10010      10.417   2006-09-12           7.0        80.0   
10011       9.520   2013-09-10           6.6       705.0   
10012       9.267   2007-03-23           7.4       990.0   
10013       9.273   2016-05-20           6.0       304.0   

                                                   genre  \
0             ['Science Fiction', 'Action', 'Adventure']   
1      ['Action', 'Adventure', 'Science Fiction', 'Fa...   
2             ['Action', 'Adventure', 'Science Fiction']   
3                        ['Action', 'Crime', 'Thriller']   
4      ['Comedy', 'Action', 'Adventure', 'Science Fic...   
...                                                  ...   
10009  ['Adventure', 'Animation', 'Comedy', 'Science ...   
10010                      ['History', 'Drama', 'Music']   
10011             ['Drama', 'Action', 'Thriller', 'War']   
10012                      ['Drama', 'Music', 'Romance']   
10013                   ['Drama', 'Mystery', 'Thriller']   

                                                overview      revenue  \
0      After finding a host body in investigative rep...  424000000.0   
1      The Eternals are a team of ancient aliens who ...  165000000.0   
2      Paul Atreides, a brilliant and gifted young ma...  331116356.0   
3      A mysterious woman recruits bank teller Ludwig...          0.0   
4      A bank teller called Guy realizes he is a back...  331096766.0   
...                                                  ...          ...   
10009  Wallace and Gromit have run out of cheese and ...          0.0   
10010  The rise and fall of salsa singer, Héctor Lavo...          0.0   
10011  An American girl on holiday in the English cou...          0.0   
10012  A vacuum repairman moonlights as a street musi...   20710513.0   
10013  Porter Wren is a Manhattan tabloid writer with...          0.0   

       runtime                                            tagline  
0         97.0                                                NaN  
1        157.0                                In the beginning...  
2        155.0                       Beyond fear, destiny awaits.  
3        127.0       Before Vegas, one locksmith became a legend.  
4        115.0     Life's too short to be a background character.  
...        ...                                                ...  
10009     23.0                                                NaN  
10010    116.0  Based on the true story of the King of Salsa, ...  
10011    101.0                            Love will lead you home  
10012     85.0            How often do you find the right person?  
10013    113.0

https://rich-d-wilkinson.github.io/MATH3030/6.1-classical-mds.html

In [3]:
test_data = np.array([[0, 0], [1, 0], [0, 1], [-1, 0], [0, -1]])

In [ ]:
def euclidean_dist(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))

def distance_matrix(vectors):
    toRet = [[0] * len(vectors) for _ in range(len(vectors))]
    for i in range(len(vectors)):
        for j in range(len(vectors)):
            dist = euclidean_dist(vectors[i], vectors[j])
            toRet[i][j] = dist
            if i != j:
                toRet[j][i] = dist
    return np.array(toRet)

def centering_matrix(n): # dimension of centering matrix
    return np.identity(n) - np.ones((n, n)) / n

In [11]:
print(euclidean_dist(test_data[2], test_data[1]))
test_dmat = distance_matrix(test_data)
print(test_dmat)

1.4142135623730951
[[0.         1.         1.         1.         1.        ]
 [1.         0.         1.41421356 2.         1.41421356]
 [1.         1.41421356 0.         1.41421356 2.        ]
 [1.         2.         1.41421356 0.         1.41421356]
 [1.         1.41421356 2.         1.41421356 0.        ]]


In [ ]:
def get_A(distance_matrix):
    return -0.5 * distance_matrix**2

def get_B(distance_matrix):
    A = get_A(distance_matrix)
    H = centering_matrix(len(distance_matrix))
    return H @ A @ H

In [14]:
print(get_A(test_dmat))
test_B = get_B(test_dmat)
print(test_B)

[[-0.  -0.5 -0.5 -0.5 -0.5]
 [-0.5 -0.  -1.  -2.  -1. ]
 [-0.5 -1.  -0.  -1.  -2. ]
 [-0.5 -2.  -1.  -0.  -1. ]
 [-0.5 -1.  -2.  -1.  -0. ]]
[[-8.49320614e-17 -1.66533454e-18 -1.66533454e-18 -1.55431223e-17
   6.66133815e-18]
 [ 3.88578059e-18  1.00000000e+00 -5.16253706e-17 -1.00000000e+00
  -7.10542736e-17]
 [ 2.88657986e-17 -5.44009282e-17  1.00000000e+00 -1.09912079e-16
  -1.00000000e+00]
 [ 5.66213743e-17 -1.00000000e+00 -1.09912079e-16  1.00000000e+00
  -1.01585407e-16]
 [ 9.54791801e-17 -9.88098492e-17 -1.00000000e+00 -9.88098492e-17
   1.00000000e+00]]


In [ ]:
def get_mds_points(vectors, new_d):
    new_d = 2
    dist_mat = distance_matrix(vectors)
    B = get_B(dist_mat)

    # get eigenvalues and eigenvectors of B
    val, vec = np.linalg.eigh(B)

    # get indices for top new_d eigenvalues
    kept_ind = np.argsort(val)[::-1][:new_d]

    # take only top eigenvalues and corresponding eigenvectors
    V_new = np.array(vec[:, kept_ind])
    lam_new = np.diag(np.sqrt(val[kept_ind]))

    return V_new @ lam_new

In [ ]:
mds_pts = get_mds_points(test_data, 2)
print('Generated points:')
print(mds_pts)

print('Dist matrix for og points:')
print(distance_matrix(test_data))
print('Dist matrix for mds points:')
print(distance_matrix(mds_pts))

Generated points
[[ 4.24805409e-17  0.00000000e+00]
 [-6.20702944e-01  7.84045824e-01]
 [-7.84045824e-01 -6.20702944e-01]
 [ 6.20702944e-01 -7.84045824e-01]
 [ 7.84045824e-01  6.20702944e-01]]
Dist matrix for og points:
[[0.         1.         1.         1.         1.        ]
 [1.         0.         1.41421356 2.         1.41421356]
 [1.         1.41421356 0.         1.41421356 2.        ]
 [1.         2.         1.41421356 0.         1.41421356]
 [1.         1.41421356 2.         1.41421356 0.        ]]
Dist matrix for mds points:
[[0.         1.         1.         1.         1.        ]
 [1.         0.         1.41421356 2.         1.41421356]
 [1.         1.41421356 0.         1.41421356 2.        ]
 [1.         2.         1.41421356 0.         1.41421356]
 [1.         1.41421356 2.         1.41421356 0.        ]]


Now to apply to our dataset